# Verify that installation from conda-forge works as intended

name: Install from conda-forge

on:
  # 05:00 UTC = 06:00 CET = 07:00 CEST
  schedule:
  - cron: "0 5 * * *"
  # Uncomment to debug
  pull_request:
   branches: [ main ]

env:
  # Name of the test environment to create
  CONDA_ENV: testenv

jobs:
  conda:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        conda_type: [anaconda, miniconda]
        extra_deps:
          - ""
          - "JPype1=1.2.1"

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.conda_type }}

    steps:
    - name: Cache Anaconda installer, conda packages
      uses: actions/cache@v2
      with:
        path: |
          $CONDA/pkgs
          ~/.conda/pkgs
          ~/anaconda3/pkgs
          ~/appdata/local/conda/conda/pkgs
          ${{ github.workspace }}/Anaconda*.*
        key: ${{ matrix.os }}-${{ matrix.conda_type }}

    - name: Setup anaconda
      if: ${{ matrix.conda == 'anaconda' }}
      # Todo change branch back to `main`
      uses: iiasa/actions/setup-conda@feature/setup-conda-action
      with:
        installer: ${{ matrix.conda }}
        version: 2019.03

    - name: Setup miniconda
      if: ${{ matrix.conda == 'miniconda' }}
      # Todo change branch back to `main`
      uses: iiasa/actions/setup-conda@feature/setup-conda-action
      with:
        installer: ${{ matrix.conda }}
        version: py39_4.9.2

    - name: Configure PowerShell for "conda activate"
      run: conda init powershell

    - name: Install message-ix
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        conda config --prepend channels conda-forge
        conda config --set channel_priority strict
        conda create --name ${{ env.CONDA_ENV }} --quiet message-ix pytest ${{ matrix.extra_deps }}

    - name: Install message-ix
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        conda config --prepend channels conda-forge
        conda create --name ${{ env.CONDA_ENV }} --quiet message-ix pytest ${{ matrix.extra_deps }}

    - name: Check
      # Check environment and run a single test from the suite to test code path to ixmp JDBCBackend
      run: |
        conda activate ${{ env.CONDA_ENV }}

        conda info

        message-ix show-versions
        ixmp --platform default list

        conda list
        pytest --pyargs message_ix.tests.test_core::test_add_cat -p ixmp.testing -p no:faulthandler
